In [ ]:
import numpy as np

array1 = [[1.,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]]
np_array1 = np.ones_like(array1)
print(np_array1)
np_array2 = np.full((5, 5), 5)
print(np_array2)

print("[출력결과1]")
np_array3 = np_array1 + np_array2
print(np_array3)

print("[출력결과2]")
array4 = [[6,1,1,1,6],[1,6,1,6,1],[1,1,6,1,1],[1,6,1,6,1],[6,1,1,1,6]]
array5 = np_array3 * array4
print(array5)

In [ ]:
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]
# [[5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]
#  [5 5 5 5 5]]
# [출력결과1]
# [[6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]
#  [6. 6. 6. 6. 6.]]
# [출력결과2]
# [[36.  6.  6.  6. 36.]
#  [ 6. 36.  6. 36.  6.]
#  [ 6.  6. 36.  6.  6.]
#  [ 6. 36.  6. 36.  6.]
#  [36.  6.  6.  6. 36.]]
